server:
  port: 8082
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server:
      host:
        - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
        - 8081
      enableKeepAlive: true
      keepAliveWithoutCalls: true
